In [1]:
# import lib
import pandas as pd

In [2]:
dataset = pd.read_csv(filepath_or_buffer = 'dataset/final_dataset_tarbase.att', sep = '\t')

In [3]:
dataset.head(10)

,Score,AlignLen,totalMFE,seedMFE,totalGC,totalAU,totalGU,totalGaps,totalMismatches,seedGC,...,Pos_12,Pos_13,Pos_14,Pos_15,Pos_16,Pos_17,Pos_18,Pos_19,Pos_20,Class
0,144.0,21,12.2,-6.5,6,7,1,4,2,3,...,4,4,4,2,5,1,1,3,5,pos
1,142.0,9,11.3,-6.5,3,6,2,0,9,3,...,5,2,5,5,3,5,3,5,5,pos
2,142.0,9,8.3,-6.5,4,7,0,0,9,3,...,5,5,5,5,5,5,2,1,5,pos
3,144.0,21,12.2,-6.5,6,7,1,4,2,3,...,4,4,4,2,5,1,1,3,5,pos
4,142.0,9,8.3,-6.5,4,7,0,0,9,3,...,5,5,5,5,5,5,2,1,5,pos
5,144.0,21,12.2,-6.5,6,7,1,4,2,3,...,4,4,4,2,5,1,1,3,5,pos
6,142.0,9,8.3,-6.5,4,7,0,0,9,3,...,5,5,5,5,5,5,2,1,5,pos
7,154.0,19,7.7,-1.5,6,8,3,1,2,3,...,1,5,2,3,2,4,2,2,1,pos
8,142.0,21,5.5,-1.7,6,5,6,2,1,4,...,1,3,2,3,3,3,5,2,4,pos
9,140.0,21,8.5,-1.7,6,7,3,3,1,4,...,5,2,2,1,3,4,2,2,4,pos